<!-- Contenido del archivo Registro.phtml -->
<div class="bg-gray-100 flex items-center justify-center ">

    <div class="bg-white p-8 rounded shadow-md w-96">
        <h2 class="text-2xl font-semibold mb-4">Registro de Usuario</h2>

        <form action="<?= $GLOBALS["link"] ?>/Public/process_register.php" method="post">
            <div class="mb-4">
                <label for="username" class="block text-gray-700 text-sm font-medium mb-2">Nombre de Usuario</label>
                <input type="text" id="username" name="username" class="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" required>
            </div>

            <div class="mb-4">
                <label for="adreca" class="block text-gray-700 text-sm font-medium mb-2">Dirección</label>
                <input type="text" id="adreca" name="adreca" class="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500">
            </div>

            <div class="mb-4">
                <label for="poblacio" class="block text-gray-700 text-sm font-medium mb-2">Población</label>
                <input type="text" id="poblacio" name="poblacio" class="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" required>
            </div>

            <div class="mb-4">
                <label for="codi_postal" class="block text-gray-700 text-sm font-medium mb-2">Código Postal</label>
                <input type="text" id="codi_postal" name="codi_postal" class="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" required>
            </div>

            <div class="mb-4">
                <label for="email" class="block text-gray-700 text-sm font-medium mb-2">Correo Electrónico</label>
                <input type="email" id="email" name="email" class="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" required>
            </div>

            <div class="mb-4">
                <label for="password" class="block text-gray-700 text-sm font-medium mb-2">Contraseña</label>
                <input type="password" id="password" name="password" class="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" required>
            </div>

            <button type="submit" class="w-full bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:border-blue-300">
                Registrarse
            </button>
        </form>
    </div>
